community_playlist_channel_id = ""

# If the bot should search for URLs in sent messages
search_messages = true

# Platforms that are supported by the bot
# Supported platforms are: spotify, youtube, youtube_music, beatsaver
active_platforms = ["spotify", "youtube"]

# What platform the bot should automatically convert URLs to
preferred_platform = "youtube"
# What platforms should have their URLs automatically converted when found in a message
disliked_platforms = []


[spotify]
# Used to obtain an api key
# https://developer.spotify.com/documentation/web-api/tutorials/getting-started#create-an-app
client_id = ""
# Used to obtain an api key
# https://developer.spotify.com/documentation/web-api/tutorials/getting-started#create-an-app
client_secret = ""
